project:
  type: website
  output-dir: docs

website:
  title: "My Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

